name: Sync Docker Hub to GitHub Container Registry

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点自动同步
  workflow_dispatch:  # 手动触发同步
  push:
    branches: [ "main" ]  # 每次推送到 main 分支时触发同步

env:
  # 镜像的源地址（Docker Hub）
  SOURCE_REGISTRY: docker.io
  SOURCE_IMAGE: cheng19930723/ml_env  # 替换为你的 Docker Hub 镜像名称
  
  # 镜像的目标地址（GitHub Container Registry）
  TARGET_REGISTRY: ghcr.io
  TARGET_IMAGE: ${{ github.repository }}  # 使用 GitHub 仓库名称作为目标镜像名称

jobs:
  sync-dockerhub-to-ghcr:
    runs-on: ubuntu-latest

    steps:
    # 登录到 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.SOURCE_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub 用户名
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}  # Docker Hub 访问令牌

    # 拉取 Docker Hub 镜像
    - name: Pull Docker Hub image
      run: |
        docker pull ${{ env.SOURCE_REGISTRY }}/${{ env.SOURCE_IMAGE }}:latest

    # 标记镜像为 GitHub Container Registry 镜像
    - name: Tag image for GitHub Container Registry
      run: |
        docker tag ${{ env.SOURCE_REGISTRY }}/${{ env.SOURCE_IMAGE }}:latest ${{ env.TARGET_REGISTRY }}/${{ env.TARGET_IMAGE }}:latest

    # 登录到 GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.TARGET_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 推送镜像到 GitHub Container Registry
    - name: Push to GitHub Container Registry
      run: |
        docker push ${{ env.TARGET_REGISTRY }}/${{ env.TARGET_IMAGE }}:latest
